### ISSUE TITLE
./app_config.js  涉及此文件的处理 在什么地方？

### ISSUE THREAD

**Issue by wwb568109135** [artskin/admin-base-tmpl#5]
document.write('<script src="./app_config.js?v='+ Math.random() +'"><\/script>');

**Comment by artskin** [comment]
源文件在`/public/app_config.js`，打包后在 `/dist/`目录下，作用是初始设置系统的一些默认值，比如默认语言，默认主题等。
`/public`下的文件不进行编译，是考虑部署现场有时需要做一些定制配置。
