### ISSUE TITLE
本地npm run dev无法login。。。

### ISSUE THREAD

**Issue by Drswith** [artskin/admin-base-tmpl#8]
在index.html切换 https://api.senseui.im/api 这个host是可以login的
但是用 http://localhost:3301/api 就不行。。mock的拦截api路径和window.appConf似乎不对应（至少userInfo和userList是不对应的）

**Comment by artskin** [comment]
感谢反馈。非常抱歉。
这个是为了部署在线Demo，mock api后来迁到这个项目里了，[express-for-vercel](https://github.com/artskin/express-for-vercel)，可以把这个项目在本地run起来就可以了。
> 稍后我把文档更新下。
